//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendRESTApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class cf_route
    {
        public cf_route()
        {
            this.cf_route_detail = new HashSet<cf_route_detail>();
        }
    
        public int route_id { get; set; }
        public string route_name { get; set; }
        public string route_type { get; set; }
        public string doc_type { get; set; }
        public string account_type { get; set; }
        public string price_over_pr_flag { get; set; }
        public decimal minimum_value { get; set; }
        public decimal maximum_value { get; set; }
        public string route_status { get; set; }
        public string create_user { get; set; }
        public string create_username { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string update_user { get; set; }
        public string update_username { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
    
        public virtual ms_doctype ms_doctype { get; set; }
        public virtual ICollection<cf_route_detail> cf_route_detail { get; set; }
    }
}
