//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendRESTApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class cf_reviewer
    {
        public int cfr_id { get; set; }
        public string saf_ref_code { get; set; }
        public string reference_type { get; set; }
        public string ad_user { get; set; }
        public string ad_fullname { get; set; }
        public string create_user { get; set; }
        public string create_username { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string update_user { get; set; }
        public string update_username { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
    }
}
