//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendRESTApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OASEntities : DbContext
    {
        public OASEntities()
            : base("name=OASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cf_delegate> cf_delegate { get; set; }
        public virtual DbSet<cf_reviewer> cf_reviewer { get; set; }
        public virtual DbSet<cf_route> cf_route { get; set; }
        public virtual DbSet<cf_route_detail> cf_route_detail { get; set; }
        public virtual DbSet<ms_company> ms_company { get; set; }
        public virtual DbSet<ms_doctype> ms_doctype { get; set; }
        public virtual DbSet<ms_plant> ms_plant { get; set; }
        public virtual DbSet<ms_tracking> ms_tracking { get; set; }
        public virtual DbSet<sys_config> sys_config { get; set; }
    }
}
