//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRESTApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_DocType
    {
        public string DocTypeCode { get; set; }
        public string DocTypeDesc { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    }
}
