//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRESTApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Tracking
    {
        public string TrackingCode { get; set; }
        public string TrackingName { get; set; }
        public string CompCode { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string UpdateUer { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    }
}
