//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRESTApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OASEntities : DbContext
    {
        public OASEntities()
            : base("name=OASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MS_Company> MS_Company { get; set; }
        public virtual DbSet<MS_DocType> MS_DocType { get; set; }
        public virtual DbSet<MS_Tracking> MS_Tracking { get; set; }
    }
}
